# Generated by Django 3.1 on 2021-02-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_sorter', '0003_auto_20210219_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='date_added',
        ),
    ]
