# Generated by Django 3.1 on 2021-02-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_sorter', '0004_remove_image_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='meme_warehouse/'),
        ),
    ]
