# Generated by Django 3.1 on 2021-02-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_sorter', '0006_auto_20210220_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagname',
            name='children',
            field=models.IntegerField(default=0),
        ),
    ]
