# Generated by Django 3.1 on 2021-02-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_sorter', '0009_auto_20210225_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='resized_image',
            field=models.ImageField(blank=True, upload_to='resizing/'),
        ),
    ]
